"use client"
/*
  Auto-generated by Spline
*/

import Spline from '@splinetool/react-spline'

export default function Scene({ ...props }) {
  return (
    <Spline scene="https://prod.spline.design/raFo8aL0K43fEw7A/scene.splinecode" />
  )
}
